version: 0.2

phases:
  pre_build:
    commands:
      - ECR_REPO=public.ecr.aws/j7u2k1c9/media-base
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - rev=$(cat Dockerfile | md5sum | awk '{print $1}')
      - |
        if aws ecr-public describe-images --repository-name j7u2k1c9/media-base --image-ids imageTag=${rev} >/dev/null 2>&1; then
          echo "Tag ${rev} already exists in ECR repository. Skipping build and push."
        else
          docker build -t ${ECR_REPO}:latest -t ${ECR_REPO}:${rev} .
          docker push ${ECR_REPO}:${rev}
        fi
